# Aula 04 - Extração de Características (Features) em Texto


*   Parte 1 - Corpus
*   Parte 2 - Extração de Características em Texto


## Parte 1 - Trabalhando com Corpora

## Parte 2 - Extração de Características



### Exemplo 1 - Implementando BOW

In [ ]:
# importando a ferramenta que irá criar a representação numérica
from sklearn.feature_extraction.text import CountVectorizer

# Criando um corpus de documentos que será usado para criação do vocabulário
documentos = [
    "gato e cachorro",
    "gato brinca com cachorro",
    "gato e lindo"
]

# Criando um objeto para ser utilizado: transformar os documentos em vetores
vectorizer = CountVectorizer()

# Criando a matriz de contagem
X = vectorizer.fit_transform(documentos)
# fit >>> cria um vocabulário das palavras
# transform >>> conta a frequência de cada palavra no corpus

# Imprimindo a Matriz e o Vocabulário gerado
print("Vocabulário: ", vectorizer.vocabulary_)
# Cada palavra do vocabulário que foi indexada aparece com seu índice

print("Matriz BOW:")
print(X.toarray())
# Mostra a frequência de cada palavra dentro da matriz


Vocabulário:  {'gato': 3, 'cachorro': 1, 'brinca': 0, 'com': 2, 'lindo': 4}
Matriz BOW:
[[0 1 0 1 0]
 [1 1 1 1 0]
 [0 0 0 1 1]]


### Exemplo 2 - Implementando BOW junto com TF-IDF

In [ ]:
# Importando as bibliotecas
from sklearn.feature_extraction.text import CountVectorizer
# Classe que transforma os documentos em vetores e realiza a contagem de frequência
from sklearn.feature_extraction.text import TfidfVectorizer
# Classe que transforma os documentos em vetores e uma contagem de frequência ponderada

# Definindo o corpus
documentos = [
    "O cachorro gosta de passear no parque.",
    "O gato dorme no sofá o dia todo.",
    "Cachorros e gatos podem ser bons amigos"
]

# Criando o modelo BoW
vectorizer_bow = CountVectorizer()
# Instanciamento da classe em objeto para ser usado
X_bow = vectorizer_bow.fit_transform(documentos)
# X_bow irá realizar a transformação do vocabulário
# fit_transform => transforma cada vetor em um documento com a contagem de frequência

# Imprimindo o Vocabulário e a Matriz
print("Vocabulário BoW:", vectorizer_bow.vocabulary_)
print("Matriz BoW:")
print(X_bow.toarray())

# Criamos um modelo TF-IDF
vectorizer_tfidf = TfidfVectorizer()
# Instanciamos a classe e transformamos os dados em objeto
X_tfidf = vectorizer_tfidf.fit_transform(documentos)
# fit irá realizar a transformação do vocabulário
# fit_transform => transforma cada vetor em um documento com a contagem de frequência ponderada

# Imprimindo o Vocabulário e a Matriz TF-IDF
print("Vocabulário TF-IDF:", vectorizer_tfidf.vocabulary_)
print("Matriz TF-IDF:")
print(X_tfidf.toarray())

Vocabulário BoW: {'cachorro': 2, 'gosta': 9, 'de': 4, 'passear': 12, 'no': 10, 'parque': 11, 'gato': 7, 'dorme': 6, 'sofá': 15, 'dia': 5, 'todo': 16, 'cachorros': 3, 'gatos': 8, 'podem': 13, 'ser': 14, 'bons': 1, 'amigos': 0}
Matriz BoW:
[[0 0 1 0 1 0 0 0 0 1 1 1 1 0 0 0 0]
 [0 0 0 0 0 1 1 1 0 0 1 0 0 0 0 1 1]
 [1 1 0 1 0 0 0 0 1 0 0 0 0 1 1 0 0]]
Vocabulário TF-IDF: {'cachorro': 2, 'gosta': 9, 'de': 4, 'passear': 12, 'no': 10, 'parque': 11, 'gato': 7, 'dorme': 6, 'sofá': 15, 'dia': 5, 'todo': 16, 'cachorros': 3, 'gatos': 8, 'podem': 13, 'ser': 14, 'bons': 1, 'amigos': 0}
Matriz TF-IDF:
[[0.         0.         0.42339448 0.         0.42339448 0.
  0.         0.         0.         0.42339448 0.32200242 0.42339448
  0.42339448 0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.42339448
  0.42339448 0.42339448 0.         0.         0.32200242 0.
  0.         0.         0.         0.42339448 0.42339448]
 [0.40824829 0.40824829 0.        

### Exemplo 3 - Realizando o Pré-processamento e a Extração de características do texto.  
Implementar as etapas de pré-processamento e representação de texto:


*   Limpeza dos dados: removendo caracteres indesejados e normalizando o texto.
*   Tokenização, stopwords, lematização/stemming.
*   Remoção de stopwords - eliminando palavras comuns que não carregam significado semântico importante.
*   Lematização - reduzindo as palavras à sua forma base.
*   Representação de Texto - convertendo o texto processado em uma matriz numérica usando o modelo Bag of Words

## Exemplo 4 - WordEmbedding utilizando Word2Vex